export const REAL_EPISODES = [
  {
    number: 10,
    title: 'El ovni de Dalnegorsk, el padre Arrupe, el Petiso Orejudo y el teatro de las locas',
    description: 'Llegamos a los 10 podcast. Hablaremos del expediente ovni de Dalnegorsk en la URSS. Conoceremos la conmovedora experiencia del padre Arrupe, quien vivió en primera persona la bomba de Hiroshima. Rescatamos la historia del Petiso Orejudo y visitamos el turbador teatro de las locas.',
    duration: '1:01:01',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-10-el-ovni-dalnegorsk-el-audios-mp3_rf_170397128_1.html',
    publishedAt: '2026-04-07',
  },
  {
    number: 9,
    title: 'Missing 411, Ham el chimpancé cósmico, la carretera de las lágrimas y la vampira de James Dean',
    description: 'Hablaremos de desapariciones misteriosas y Missing 411. Recordaremos la vida de Ham el chimpancé cósmico. Viajamos hasta Canadá para conocer la carretera de las lágrimas. Y analizaremos la tortuosa relación de James Dean con una Vampira.',
    duration: '44:52',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-9-missing-411-ham-el-audios-mp3_rf_169993324_1.html',
    publishedAt: '2026-03-31',
  },
  {
    number: 8,
    title: 'Los mensajes del pasado, la inundación de la cerveza, el crimen de Lava Lake y el cine y Ed Gein',
    description: 'El extraño caso de los mensajes de Meadow Cottage en Inglaterra. La inundación de la cerveza de Londres. Un extraño caso sin resolver: el triple asesinato de Lava Lake. Y la extraña atracción que siente la sociedad por Ed Gein.',
    duration: '1:05:07',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-8-los-mensajes-del-pasado-audios-mp3_rf_169582376_1.html',
    publishedAt: '2026-03-17',
  },
  {
    number: 7,
    title: 'Los círculos de hadas, la masacre de mascotas, la pandilla satánica y el Gabinete del Doctor Caligari',
    description: 'Los misteriosos círculos de hadas. La masacre de mascotas británica durante la II Guerra Mundial. Una pandilla satánica que sembró el terror en Chicago. Y los misterios de la primera película de terror: el Gabinete del Doctor Caligari.',
    duration: '59:19',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-7-los-ciculos-hadas-la-audios-mp3_rf_169220514_1.html',
    publishedAt: '2026-03-10',
  },
  {
    number: 6,
    title: 'El otro Diatlov, Norton I de los EE.UU, el asesino Amish y el Coronel Ignotus',
    description: 'El suceso terrorífico de Khamar Daban. Norton I, el Emperador de los Estados Unidos. Ed Gingerich, el asesino Amish. Y un homenaje al escritor de Ciencia Ficción español olvidado: el Coronel Ignotus.',
    duration: '46:02',
    ivooxUrl: 'https://www.ivoox.com/elexpediente-0-6-el-otro-diatlov-norton-i-los-audios-mp3_rf_168696514_1.html',
    publishedAt: '2026-02-24',
  },
  {
    number: 5,
    title: 'Montes misteriosos, la catástrofe de Mayak, la asesina de esclavos y Pesadilla en Elm Street',
    description: 'Cinco montañas españolas cargadas de misterio. El accidente nuclear de Mayak, antes de Chernobyl. La siniestra madame Lalaurie en la Nueva Orleans del XIX. Y la historia real de Freddy Krueger.',
    duration: '56:16',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-5-montes-misteriosos-catastrofe-audios-mp3_rf_168287771_1.html',
    publishedAt: '2026-02-17',
  },
  {
    number: 4,
    title: 'Cicada 3301, el doctor MacDowell, el crimen de Emmet Till y la pintora medium',
    description: 'Los extraños mensajes de Cicada 3301. La oscura historia de un resurreccionista de cadáveres. El horrible asesinato racial de Emmet Till. Y Hilma Al Klint, la pintora que creó el arte abstracto de la mano de espíritus.',
    duration: '49:40',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-4-cicada-3301-doctor-audios-mp3_rf_167543515_1.html',
    publishedAt: '2026-02-10',
  },
  {
    number: 3,
    title: 'El caso Schirmer, Danniken y los premios IG, la bestia de Baltimore, Otto Dix',
    description: 'El caso OVNI del oficial Herbert Schirmer. Los premios IG Nobel y Erich Von Danniken. La bestia de Baltimore. Y el pintor Otto Dix en los años posteriores a la Primera Guerra Mundial.',
    duration: '59:45',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-3-el-caso-schirmer-danniken-los-audios-mp3_rf_167167820_1.html',
    publishedAt: '2026-01-27',
  },
  {
    number: 2,
    title: 'Leyendas japonesas, juicios a animales, el monstruo de los manglares y The Lash of the Penitentes',
    description: '5 leyendas urbanas japonesas. Juicios históricos a animales. El monstruo de los manglares, asesino en serie de Ecuador y Colombia. Y la película maldita The Lash of the Penitentes.',
    duration: '1:06:58',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-2-leyendas-japonesas-juicios-a-audios-mp3_rf_166838973_1.html',
    publishedAt: '2026-01-20',
  },
  {
    number: 1,
    title: 'El síndrome de la Habana, Barnum, Jack the Stripper y el robo de la Gioconda',
    description: 'El primer episodio de El Expediente 0. El síndrome de la Habana. P.T. Barnum, el mayor showman del mundo. Los crímenes de Jack the Stripper. Y el enigmático robo de la Mona Lisa.',
    duration: '1:01:53',
    ivooxUrl: 'https://www.ivoox.com/expediente-0-el-sindrome-habana-audios-mp3_rf_166244557_1.html',
    publishedAt: '2026-01-09',
  },
]

export const PODCAST_SECTIONS = [
  { id: 'inexplicable', label: 'Inexplicable', description: 'Fenómenos sin explicación, OVNIs y misterios sin resolver', icon: '◈' },
  { id: 'archivo', label: 'Archivo Histórico', description: 'Historia curiosa, desconocida y sorprendente', icon: '⊞' },
  { id: 'hemeroteca', label: 'Hemeroteca Negra', description: 'True crime, crímenes y crónica negra', icon: '◉' },
  { id: 'contracultural', label: 'Contracultural', description: 'Arte, cine y cultura en sus facetas más extrañas', icon: '◇' },
]
